# Site settings
title: so, it's come to this...
email: 
description: > # this means to ignore newlines until "baseurl:"
  I'll hear a technique or technology mentioned, it stirs around in my brain, and then I fall down that rabbit hole. If I make it back with my sanity intact, I'll usually write about it here.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://soitscometothis.net" # the base hostname & protocol for your site
twitter_username: nuclearzenfire
github_username:  nuclearzenfire

# Build settings
markdown: kramdown
paginate: 10
paginate_path: "page:num"